#!/usr/bin/env ruby

require 'json'
require "sqlite3"

# $fd = open("/tmp/credhelper.out", 'a')

class Database
  def initialize(data_dir="db")
    if !File.exists?(data_dir)
      Dir.mkdir(data_dir)
    end
    db_path = File.join(data_dir, "creds.db")
    if !File.exists?(db_path)

      @db = SQLite3::Database.new(db_path)

      @db.execute <<-SQL
        create table creds (
          url string primary key,
          username string,
          secret string
      );
      SQL
    else
      @db = SQLite3::Database.open(db_path)
    end
  end

  def list
# $fd.puts(">> list")
    result = @db.execute("select url, username from creds")
# $fd.puts("list: #{ result }")
# $fd.puts("list: #{ Hash[result] }")
    return JSON.generate(Hash[result])
  end

  def get(url)
# $fd.puts(">> get(#{url}")
    result = @db.execute("select * from creds where url=?", [url.strip])
    # $fd.puts("... #{result}")

    if result.size == 0
      puts "credentials not found in native keychain"
      exit 1
    end
    vals = result[0]
    return JSON.generate(Hash[%w/ServerURL Username Secret/.zip(vals)])
  end

  def store(data)
    # $fd.puts("store: #{ data }")
    obj = JSON.parse(data)
    erase(obj['ServerURL'])
    @db.execute("insert into creds values(?, ?, ?)", [obj.fetch('ServerURL'), obj.fetch('Username'), obj.fetch('Secret')])
  end

  def erase(url)
    @db.execute("delete from creds where url = ?", url)
  end
end

db = Database.new(File.join(ENV['HOME'], 'lab', 'credhelper', 'db'))

cmd = ARGV.shift
if cmd == "list"
  puts db.list
  # $fd.puts("... done")
  exit 0
end

if !cmd
  abort "Error: no command given"
end
if !%w/get store erase/.include?(cmd)
  abort "Error: command #{cmd} not recognized"
end

data = (ARGV[0] || STDIN.read()).strip

case cmd
when "get"
  puts db.get(data)
when "store"
  puts db.store(data)
when "erase"
  db.erase(data)
else
  puts "Error: command #{cmd} not recognized"
end

# $fd.close
